parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string 

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy  ${{ parameters.stageName }}'
  jobs:
  - deployment: DeploytoIIS
    displayName: 'Deploy applications to ${{parameters.environment}} environment'
    timeoutInMinutes: 10
    environment: 
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy: 
        runOnce:
          deploy:
            steps:
              - template: ./deploy-applicationpool.yml   
              
  - template: ./deploy-template.yml
    parameters:
      varfilename: vars-web1
      environment: ${{ parameters.environment }}
  
#  - deployment: DeploytoIIS2
#    displayName: 'Deploy applications to ${{parameters.environment}} environment'
#    timeoutInMinutes: 10
#    dependsOn: DeploytoIIS
#    environment: 
#      name: ${{ parameters.environment }}
#      resourceType: VirtualMachine
#    strategy: 
#        runOnce:
#          deploy:
#            steps:
#              - template: ./deploy-web.yml
#                parameters:
#                  websiteName: 'testing'
#                  packageName: 'Web1' 
#                  applicationPool: 'mcoapi'
#                  port: '98'
              
                
          