parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string 

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy  ${{ parameters.stageName }}'
  variables:
    Release.EnvironmentName: ${{ parameters.environment }}
  jobs:
  - deployment: DeploytoIIS
    displayName: 'Deploy applications to ${{parameters.environment}} environment'
    timeoutInMinutes: 10
    environment: 
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy: 
        runOnce:
          deploy:
            steps:
              - download: none
              - powershell: | 
                      # check if https binding already exsits for the site
                      if (!(Get-IISSiteBinding -Name B2B -Protocol "http" ))
                      {
                            Write-Host "##vso[task.setvariable variable=isHttpsMissing;]true"
                      }
                displayName: 'Https Exists'
                
              - task: FileTransform@1
                displayName: 'Config Transformation'
                condition: eq(variables['isHttpsMissing'], true)  
                inputs:
                  folderPath: 'C:\Service\a\ServiceAcknowledge'
                  enableXmlTransform: true
                  xmlTransformationRules: '-transform App.$(Release.EnvironmentName).config -xml *.exe.config'        
              
              
#  - template: ./deploy-template.yml
#    parameters:
#      varfilename: vars-web1
#      environment: ${{ parameters.environment }}
  