parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy  ${{ parameters.stageName }}'
  jobs:
  - deployment: deploymentProd1
    displayName: 'Deployment'
    timeoutInMinutes: 10
    variables:
      - template: ./vars-web.yml 
    environment: 
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy: 
        runOnce:
          preDeploy:
            steps:
            - script: echo initialize, cleanup, backup, install certs
          deploy:
            steps:
            
            - task: IISWebAppManagementOnMachineGroup@0
              displayName: 'Stop Application Pool'
              inputs:
                IISDeploymentType: 'IISApplicationPool'
                ActionIISApplicationPool: 'StopAppPool'
                StartStopRecycleAppPoolName: 'mcoapi'
            
            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteAdditionalTariff)
                packageName: $(packageSiteAdditionalTariff)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteB2B)
                packageName: $(packageSiteB2B)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteBusinessPartner)
                packageName: $(packageSiteBusinessPartner)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteCustomsInventory)
                packageName: $(packageSiteCustomsInventory)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteDeclarationSetting)
                packageName: $(packageSiteDeclarationSetting)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteDeclarationStatus)
                packageName: $(packageSiteDeclarationStatus)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteDropDownValues)
                packageName: $(packageSiteDropDownValues)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteLotAndJobNumber)
                packageName: $(packageSiteLotAndJobNumber)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteMCO)
                packageName: $(packageSiteMCO)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteProduct)
                packageName: $(packageSiteProduct)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteReceivingCountry)
                packageName: $(packageSiteReceivingCountry)

            - template: deploy-web.yml
              parameters:
                websiteName: $(webSiteTallySheet)
                packageName: $(packageSiteTallySheet)
                
            - task: IISWebAppManagementOnMachineGroup@0
              displayName: 'Start Application Pool'
              inputs:
                IISDeploymentType: 'IISApplicationPool'
                ActionIISApplicationPool: 'StartAppPool'
                StartStopRecycleAppPoolName: 'mcoapi'
          on: 
            failure: 
              steps: 
              - script: echo clean-up, rollback...   
            success: 
              steps: 
              - script: echo checks passed, notify...