parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string
- name: 'applications' 
  type: object  

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy  ${{ parameters.stageName }}'
  jobs:
  - deployment: DeploytoIIS
    displayName: 'Deploy applications to ${{parameters.environment}} environment'
    timeoutInMinutes: 10
    variables:
      - template: ./vars-web.yml
      - template: ./vars-windows.yml      
    environment: 
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy: 
        runOnce:
          preDeploy:
            steps:
            - script: echo initialize, cleanup
          deploy:
            steps:
            
            - template: deploy-windows.yml
              parameters:
                packageName: ${{variables.packageServiceAcknowledge}}
                serviceName: ${{variables.serviceAcknowledge}}

                
          on: 
            failure: 
              steps: 
              - script: echo clean-up, rollback...   
            success: 
              steps: 
              - script: echo checks passed, notify...