parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string 

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy  ${{ parameters.stageName }}'
  jobs:
  - deployment: DeploytoIIS
    displayName: 'Deploy applications to ${{parameters.environment}} environment'
    timeoutInMinutes: 10
    environment: 
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy: 
        runOnce:
          deploy:
            steps:
              - download: none
              - template: ./deploy-applicationpool.yml   
              
  - template: ./deploy-template.yml
    parameters:
      varfilename: vars-web1
      environment: ${{ parameters.environment }}
  