parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string
- name: 'applications' 
  type: object  

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy  ${{ parameters.stageName }}'
  jobs:
  - deployment: deploymentProd1
    displayName: 'Deployment'
    timeoutInMinutes: 10
    variables:
      - template: ./vars-web.yml
      - template: ./vars-windows.yml      
    environment: 
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy: 
        runOnce:
          preDeploy:
            steps:
            - script: echo initialize, cleanup, backup, install certs
          deploy:
            steps:
            
            - template: iis.yml
            
#            - task: IISWebAppManagementOnMachineGroup@0
#              displayName: 'Stop Application Pool'
#              inputs:
#                IISDeploymentType: 'IISApplicationPool'
#                ActionIISApplicationPool: 'StopAppPool'
#                StartStopRecycleAppPoolName: ${{variables.applicationPoolApi}}
            
            - ${{ if eq(parameters.applications.additionalTariff, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteAdditionalTariff}}
                  packageName: ${{variables.packageAdditionalTariff}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 81

            - ${{ if eq(parameters.applications.b2b, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteB2B}}
                  packageName: ${{variables.packageB2B}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 82

            - ${{ if eq(parameters.applications.businessPartner, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteBusinessPartner}}
                  packageName: ${{variables.packageBusinessPartner}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 83

            - ${{ if eq(parameters.applications.customsInventory, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteCustomsInventory}}
                  packageName: ${{variables.packageCustomsInventory}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 84

            - ${{ if eq(parameters.applications.declarationSetting, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteDeclarationSetting}}
                  packageName: ${{variables.packageDeclarationSetting}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 85

            - ${{ if eq(parameters.applications.declarationStatus, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteDeclarationStatus}}
                  packageName: ${{variables.packageDeclarationStatus}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 86

            - ${{ if eq(parameters.applications.dropDownValues, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteDropDownValues}}
                  packageName: ${{variables.packageDropDownValues}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 87

            - ${{ if eq(parameters.applications.lotAndJobNumber, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteLotAndJobNumber}}
                  packageName: ${{variables.packageLotAndJobNumber}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 88

            - ${{ if eq(parameters.applications.mco, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteMCO}}
                  packageName: ${{variables.packageMCO}}
                  applicationPool: ${{variables.applicationPoolWeb}}
                  port: 80

            - ${{ if eq(parameters.applications.product, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteProduct}}
                  packageName: ${{variables.packageProduct}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 89

            - ${{ if eq(parameters.applications.receivingCountry, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteReceivingCountry}}
                  packageName: ${{variables.packageReceivingCountry}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 90

            - ${{ if eq(parameters.applications.tallySheet, true) }}:
              - template: deploy-web.yml
                parameters:
                  websiteName: ${{variables.webSiteTallySheet}}
                  packageName: ${{variables.packageTallySheet}}
                  applicationPool: ${{variables.applicationPoolApi}}
                  port: 91
                
            - task: IISWebAppManagementOnMachineGroup@0
              displayName: 'Recycle Application Pool'
              inputs:
                IISDeploymentType: 'IISApplicationPool'
                ActionIISApplicationPool: 'RecycleAppPool'
                StartStopRecycleAppPoolName: ${{variables.applicationPoolApi}}
                
            - ${{ if eq(parameters.applications.parameters.acknowledge, true) }}:
              - template: deploy-windows.yml
                parameters:
                  packageName: ${{variables.packageServiceAcknowledge}}

            - ${{ if eq(parameters.applications.parameters.partnerService, true) }}:
              - template: deploy-windows.yml
                parameters:
                  packageName: ${{variables.packageServiceBusinessPartner}}
                  
            - ${{ if eq(parameters.applications.parameters.consignmentService, true) }}:
              - template: deploy-windows.yml
                parameters:
                  packageName: ${{variables.packageServiceConsignment}}
                  
            - ${{ if eq(parameters.applications.parameters.declarationService, true) }}:
              - template: deploy-windows.yml
                parameters:
                  packageName: ${{variables.packageServiceDeclaration}}

            - ${{ if eq(parameters.applications.parameters.notificationService, true) }}:
              - template: deploy-windows.yml
                parameters:
                  packageName: ${{variables.packageServiceInvoiceNotification}}
                  
            - ${{ if eq(parameters.applications.parameters.classificationService, true) }}:
              - template: deploy-windows.yml
                parameters:
                  packageName: ${{variables.packageServiceProductClassification}}

            - ${{ if eq(parameters.applications.parameters.shipmentService, true) }}:
              - template: deploy-windows.yml
                parameters:               
                  packageName: ${{variables.packageServiceShipment}}

            - ${{ if eq(parameters.applications.parameters.itemService, true) }}:
              - template: deploy-windows.yml
                parameters:          
                  packageName: ${{variables.packageServiceWorklistItem}}
                
          on: 
            failure: 
              steps: 
              - script: echo clean-up, rollback...   
            success: 
              steps: 
              - script: echo checks passed, notify...