parameters:
- name: 'stageName'
  type: string
- name: 'environment'
  type: string
  values:
  - DEV
  - PROD

stages:
- stage: ${{ parameters.stageName }}
  displayName: '${{ parameters.stageName }} - Deploy'
  jobs:
  - deployment: deploymentuniqued 
    displayName: 'Deployment'
    timeoutInMinutes: 10
    environment: 
       name: ${{ parameters.environment }}
       resourceType: VirtualMachine
    strategy: 
       runOnce:
         preDeploy:
          steps:
          - script: echo initialize, cleanup, backup, install certs
         deploy:
          steps:
          - script: echo deploy iis and windows service
         on: 
          failure: 
            steps: 
            - script: echo clean-up, rollback...   
          success: 
            steps: 
            - script: echo checks passed, notify...