# Description: Release pipleline.

parameters:
    
  - name: additionalTariff
    displayName: AdditionalTariff
    type: boolean
    default: true
    
  - name: b2b
    displayName: B2B
    type: boolean
    default: true
    
  - name: businessPartner
    displayName: BusinessPartner
    type: boolean
    default: true
    
  - name: customsInventory
    displayName: CustomsInventory
    type: boolean
    default: true
    
  - name: declarationSetting
    displayName: DeclarationSetting
    type: boolean
    default: true
    
  - name: declarationStatus
    displayName: DeclarationStatus
    type: boolean
    default: true
    
  - name: dropDownValues
    displayName: DropDownValues
    type: boolean
    default: true
    
  - name: lotAndJobNumber
    displayName: LotAndJobNumber
    type: boolean
    default: true

name: XCO_Release_$(Date:yyyymmdd)$(Rev:r)

# On-demand for development purpose
trigger: none

variables:
- template: ./Templates/vars.yml
  
stages: 
 - stage: build
   displayName: 'Build Solution'
   jobs:
   - job: 'BuildAndPublish'
     displayName: 'Build and Publish'
#     variables:
#      - template: ./Templates/vars-web.yml  # variables to be used later    
     pool:
      vmImage: 'windows-2022' #windows-latest

     steps:
     
#      - template: ./Templates/param-test.yml
#        parameters:
#          webApplication: ${{parameters.webApplication}}
      
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
            packageType: 'sdk'
            version: '6.0.x'
            includePreviewVersions: true
            
      - task: NuGetToolInstaller@1
      
      - task: NuGetCommand@2
        displayName: 'Restore NuGet Package'
        name: 'RestorePackage'
        inputs:
            command: 'restore'
            restoreSolution: $(solution)
            feedsToUse: 'select'

      - task: VSBuild@1
        displayName: 'Build Solution' 
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
            
      - template: ./Templates/multiproject-web-build.yml
#      - template: ./Templates/multiproject-windows-build.yml
      
 - template: ./Templates/deploy.yml
   parameters:
    stageName: local
    environment: local


# Comment in the end


