# Description: Release pipleline.

parameters:
    
  - name: additionalTariff
    displayName: AdditionalTariff Api
    type: boolean
    default: true
    
  - name: b2b
    displayName: B2B Api
    type: boolean
    default: true
    
  - name: businessPartner
    displayName: BusinessPartner Api
    type: boolean
    default: true
    
  - name: customsInventory
    displayName: CustomsInventory Api
    type: boolean
    default: true
    
  - name: declarationSetting
    displayName: DeclarationSetting Api
    type: boolean
    default: true
    
  - name: declarationStatus
    displayName: DeclarationStatus Api
    type: boolean
    default: true
    
  - name: dropDownValues
    displayName: DropDownValues Api
    type: boolean
    default: true
    
  - name: lotAndJobNumber 
    displayName: LotAndJobNumber Api
    type: boolean
    default: true
    
  - name: mco
    displayName: MCO Web
    type: boolean
    default: true

  - name: product
    displayName: Product Api
    type: boolean
    default: true
    
  - name: receivingCountry
    displayName: ReceivingCountry Api
    type: boolean
    default: true
    
  - name: tallySheet
    displayName: TallySheet Api
    type: boolean
    default: true

  - name: acknowledge
    displayName: Acknowledge Service
    type: boolean
    default: true
    
  - name: partnerService
    displayName: Business Partner Service
    type: boolean
    default: true

  - name: consignmentService
    displayName: Consignment Event Service
    type: boolean
    default: true

  - name: declarationService
    displayName: Declaration Service
    type: boolean
    default: true

  - name: notificationService
    displayName: Invoice Notification Service
    type: boolean
    default: true

  - name: classificationService
    displayName: Product Classification Service
    type: boolean
    default: true

  - name: shipmentService
    displayName: Shipment Event Service
    type: boolean
    default: true

  - name: itemService
    displayName: Worklist Item Service
    type: boolean
    default: true

name: XCO_Release_$(Date:yyyymmdd)$(Rev:r)

# On-demand for development purpose
trigger: none

variables:
- template: ./Templates/vars.yml
  
stages: 
 - stage: build
   displayName: 'Build Solution'
   jobs:
   - job: 'BuildAndPublish'
     displayName: 'Build and Publish'
#     variables:
#      - template: ./Templates/vars-web.yml  # variables to be used later    
     pool:
      vmImage: 'windows-2022' #windows-latest

     steps:
     
#      - template: ./Templates/param-test.yml
#        parameters:
#          webApplication: ${{parameters.webApplication}}
      
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
            packageType: 'sdk'
            version: '6.0.x'
            includePreviewVersions: true
            
      - task: NuGetToolInstaller@1
      
      - task: NuGetCommand@2
        displayName: 'Restore NuGet Package'
        name: 'RestorePackage'
        inputs:
            command: 'restore'
            restoreSolution: $(solution)
            feedsToUse: 'select'

      - task: VSBuild@1
        displayName: 'Build Solution' 
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
            
      - template: ./Templates/multiproject-web-build.yml
#      - template: ./Templates/multiproject-windows-build.yml
      
 - template: ./Templates/deploy.yml
   parameters:
    stageName: local
    environment: local


# Comment in the end


